#!/usr/bin/env ansible-playbook
# This is a demo client. Run this playbook after running the demo-cluster to get a client with
# a kubeconfig file with access to the demo cluster
---
- name: Setup a Container Security Ubuntu Machine
  hosts: localhost
  become: yes


  tasks:
  - import_tasks: ansible_tasks/setup_docker.yml
  - import_tasks: ansible_tasks/setup_docker_compose.yml
  - import_tasks: ansible_tasks/setup_trivy.yml
  - import_tasks: ansible_tasks/setup_helm.yml
  - import_tasks: ansible_tasks/setup_auger.yml
  - import_tasks: ansible_tasks/setup_etcdctl.yml
  - import_tasks: ansible_tasks/setup_gvisor.yml
  - import_tasks: ansible_tasks/setup_rbac_tools.yml
  - import_tasks: ansible_tasks/setup_nmap.yml
  - import_tasks: ansible_tasks/setup_kind.yml
  - import_tasks: ansible_tasks/setup_kubectl.yml
  - import_tasks: ansible_tasks/setup_kubectl_completion.yml
  - import_tasks: ansible_tasks/setup_kubectl_tools.yml
  - import_tasks: ansible_tasks/setup_whaler_dive.yml